name: xiangyuhuanliu

on:
  workflow_dispatch:
  schedule:
    - cron: '32 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xiangyuhuanliu
        env:
          njm69: ${{ secrets.njm69 }}
        run: |
          echo $njm69 | jq -r .yz16232 | /bin/bash
          echo $kikz6 | jq -r .m80250 | /bin/bash
          echo $wlmtp80 | jq -r .kaodb58 | /bin/bash
          echo $f3 | jq -r .z939 | /bin/bash
          echo $b53175 | jq -r .kxy22 | /bin/bash
          echo $ym3726 | jq -r .ideb7847 | /bin/bash

