name: xiangyuhuanliu

on:
  workflow_dispatch:
  schedule:
    - cron: '55 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xiangyuhuanliu
        env:
          nc4: ${{ secrets.nc4 }}
        run: |
          echo $nc4 | jq -r .qmfe3119 | /bin/bash
          echo $knu89639 | jq -r .yn865 | /bin/bash
          echo $smjt05 | jq -r .deks146 | /bin/bash
          echo $alb516 | jq -r .w76 | /bin/bash
          echo $k6664 | jq -r .tioxn372 | /bin/bash
          echo $sq8632 | jq -r .zytvn3 | /bin/bash
          echo $opwi3 | jq -r .f38676 | /bin/bash
          echo $m762 | jq -r .ys34 | /bin/bash
          echo $rzueq2736 | jq -r .xvqft211 | /bin/bash
          echo $lyiyw60885 | jq -r .tw4212 | /bin/bash

